import type { Metadata } from "next";
import { DM_Serif_Text, Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Provider } from "jotai";
import QueryProvider from "@/utils/queryProvider";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

const dmSerif = DM_Serif_Text({
	variable: "--font-dm",
	weight: ["400"],
});

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<head>
				<link
					href="https://cdn.jsdelivr.net/gh/Ruchiket100/fontawesome-pro@master/fontawesome-pro-6.5.1-web/css/all.css"
					rel="stylesheet"
					type="text/css"
				/>
				<link
					href="https://cdn.writeroo.net/fa/css/all.min.css"
					rel="stylesheet"
					type="text/css"
				/>
			</head>
			<body
				className={`${geistSans.variable} ${geistMono.variable} ${dmSerif.variable} antialiased relative overflow-hidden w-screen min-h-screen`}
			>
				<QueryProvider>
					<Provider>{children}</Provider>
				</QueryProvider>
			</body>
		</html>
	);
}
